"""What the About panel needs: the licence, the notices, and what changed.

`identity.py` answers "what is this and where is its source". This module answers
the two things that need files rather than constants:

* **Third-party notices.** `docs/notices.json` is generated by
  `scripts/generate_notices.py` and ships in the bundle (`docs/RELEASE.md` §5).
  The About panel renders it so a user can see every dependency's licence
  without a network call, which is half of what the AGPL's §6 offer of source is
  for. `THIRD_PARTY_NOTICES.md` — the hand-written donor provenance — carries the
  other half, and its "no open distribution gate remains" line is asserted by
  `test/studio/test_repo_contract.py`.
* **What's new.** The headline of each recent `CHANGELOG.md` section. Only the
  headlines: they are plain sentences about what changed for the person using
  the app, while the bodies below them are engineering notes full of file paths.

Both files are found next to the package in a packaged build and at the
repository root in a checkout; `CONTENT_STUDIO_DOCS_DIR` overrides both, so the
Tauri shell can point at whatever it laid down in the bundle.
"""

from __future__ import annotations

import json
import os
import re
from pathlib import Path

from .identity import version_payload

# `## 2026-09-02 21:58:53 +08:00 — A drawn character sheet is shown …`
# The date is the first token; the headline is everything past the em dash. A
# section without one is skipped rather than shown with a mangled title.
_CHANGELOG_HEADING = re.compile(r"^##\s+(\d{4}-\d{2}-\d{2})[^—\n]*—\s*(.+?)\s*$")

WHATS_NEW_LIMIT = 5


def docs_root() -> Path:
    """Where LICENSE, THIRD_PARTY_NOTICES.md, CHANGELOG.md and docs/ live."""
    override = os.environ.get("CONTENT_STUDIO_DOCS_DIR", "").strip()
    if override:
        return Path(override).expanduser()
    return Path(__file__).resolve().parents[2]


def notices() -> dict:
    """The generated dependency-licence roll-up, or an honest empty answer.

    A build that forgot to run `scripts/generate_notices.py` must not take the
    About panel down with it: the panel still shows the product's own licence and
    source, and says the dependency list is missing rather than showing nothing.
    """
    path = docs_root() / "docs" / "notices.json"
    try:
        loaded = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {"available": False, "python": {"packages": []}, "npm": {}, "unresolved": []}
    if not isinstance(loaded, dict):
        return {"available": False, "python": {"packages": []}, "npm": {}, "unresolved": []}
    return {"available": True, **loaded}


def whats_new(limit: int = WHATS_NEW_LIMIT) -> list[dict[str, str]]:
    """The most recent changelog headlines, newest first."""
    path = docs_root() / "CHANGELOG.md"
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return []
    entries: list[dict[str, str]] = []
    for line in text.splitlines():
        match = _CHANGELOG_HEADING.match(line)
        if not match:
            continue
        entries.append({"date": match.group(1), "title": match.group(2)})
        if len(entries) >= max(1, limit):
            break
    return entries


def about_payload() -> dict:
    """The body of GET /api/about.

    Everything here is about the software, not the machine it runs on or the
    person using it: the same rule `identity.version_payload` follows, because
    this route is unauthenticated for the same reason.
    """
    return {
        **version_payload(),
        "notices": notices(),
        "whats_new": whats_new(),
    }
