// The device key is only useful if the gateway's sealer and this browser agree
// on the wire format, byte for byte. They are written in different languages
// against different crypto libraries, and a mismatch (iv/dek order, base64url
// padding, OAEP digest) fails in exactly the same way a wrong recipient does —
// a clip that simply refuses to open, long after it was generated.
//
// So this seals with the REAL media_seal.py against a key generated by the REAL
// WebCrypto, then opens it with the same steps deviceIdentity.decryptWithDevice
// performs. Skips itself if the repo's python venv is not present.
import assert from 'node:assert/strict';
import test from 'node:test';
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, writeFileSync, existsSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = fileURLToPath(new URL('.', import.meta.url));
const repoRoot = resolve(here, '..', '..', '..');
const python = join(repoRoot, '.venv', 'bin', 'python');
const sealer = join(repoRoot, 'packages', 'media-gateway', 'media_seal.py');

const runnable = existsSync(python) && existsSync(sealer);

function toB64url(buffer) {
  return Buffer.from(buffer).toString('base64').replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

function fromB64url(text) {
  return Buffer.from(String(text).replace(/-/g, '+').replace(/_/g, '/'), 'base64');
}

test('media sealed by the gateway to a device key opens with that device key', { skip: !runnable }, async () => {
  const subtle = globalThis.crypto.subtle;
  // Exactly the parameters deviceIdentity.js generates with.
  const keyPair = await subtle.generateKey(
    { name: 'RSA-OAEP', modulusLength: 2048, publicExponent: new Uint8Array([1, 0, 1]), hash: 'SHA-256' },
    false,
    ['encrypt', 'decrypt'],
  );
  const spki = toB64url(await subtle.exportKey('spki', keyPair.publicKey));

  const dir = mkdtempSync(join(tmpdir(), 'device-envelope-'));
  try {
    const pubFile = join(dir, 'device.pub');
    const plainFile = join(dir, 'clip.bin');
    const envelopeFile = join(dir, 'clip.e2e');
    // Non-trivial payload: long enough to cross a block boundary.
    const plaintext = Buffer.from('hivemind device seal interop — '.repeat(500), 'utf8');
    writeFileSync(pubFile, spki, 'utf8');
    writeFileSync(plainFile, plaintext);

    execFileSync(python, [sealer, '--pub', `@${pubFile}`, '--in', plainFile, '--out', envelopeFile]);
    const envelope = JSON.parse(readFileSync(envelopeFile, 'utf8'));

    // The exact steps decryptWithDevice performs.
    const dekRaw = await subtle.decrypt({ name: 'RSA-OAEP' }, keyPair.privateKey, fromB64url(envelope.wrapped_dek));
    const dek = await subtle.importKey('raw', dekRaw.slice(12), { name: 'AES-GCM', length: 256 }, false, ['decrypt']);
    const iv = new Uint8Array(dekRaw.slice(0, 12));
    const opened = await subtle.decrypt({ name: 'AES-GCM', iv }, dek, fromB64url(envelope.ciphertext));

    assert.deepEqual(Buffer.from(opened), plaintext);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test('an envelope sealed to a different device refuses this one', { skip: !runnable }, async () => {
  // The isolation property itself: possession of the media is not access to it.
  const subtle = globalThis.crypto.subtle;
  const params = { name: 'RSA-OAEP', modulusLength: 2048, publicExponent: new Uint8Array([1, 0, 1]), hash: 'SHA-256' };
  const theirs = await subtle.generateKey(params, false, ['encrypt', 'decrypt']);
  const mine = await subtle.generateKey(params, false, ['encrypt', 'decrypt']);

  const dir = mkdtempSync(join(tmpdir(), 'device-envelope-'));
  try {
    const pubFile = join(dir, 'device.pub');
    const plainFile = join(dir, 'clip.bin');
    const envelopeFile = join(dir, 'clip.e2e');
    writeFileSync(pubFile, toB64url(await subtle.exportKey('spki', theirs.publicKey)), 'utf8');
    writeFileSync(plainFile, Buffer.from('not for you', 'utf8'));

    execFileSync(python, [sealer, '--pub', `@${pubFile}`, '--in', plainFile, '--out', envelopeFile]);
    const envelope = JSON.parse(readFileSync(envelopeFile, 'utf8'));

    await assert.rejects(
      subtle.decrypt({ name: 'RSA-OAEP' }, mine.privateKey, fromB64url(envelope.wrapped_dek)),
    );
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});
