// Cinema Studio — React redesign of components/CinemaStudio.js.
// Camera-simulated image generation: a camera rig (body / lens / focal / aperture)
// compiles a cinematic prompt via buildNanoBananaPrompt, generated by nano-banana-pro.
//
// Port rules honored here:
// - src/lib/** consumed unchanged; buildNanoBananaPrompt assembles the final prompt
//   with identical ordering; the generateImage call shape is byte-preserved.
// - Preferences persist to localStorage 'cinema_generation_preferences' via a
//   normalizer that is behaviorally identical to the old normalizeCinemaPreferences
//   (the old file stays on disk so its exported normalizer keeps satisfying the
//   generationSettingsPersistence test).
// - History persists to 'cinema_history' (slice 0..50), same entry shape.
// - Every media src goes through useMediaSrc (E2E decrypt, fail-open).
// - alert() → toast.error(); the two competing camera UIs (full-screen wheel overlay
//   + collapsible builder) collapse to ONE controlled rig in the left panel, which
//   fixes the old overlay/builder desync and body-mounted overlay leak for free.
// - The old "Regenerate clears the prompt then re-clicks Generate (no-ops)" bug is
//   fixed: Regenerate restores that shot's setup and generates. (Documented deviation.)
import { useEffect, useRef, useState } from 'react';
import { toast } from 'react-hot-toast';

import { muapi } from '../lib/muapi.js';
import { buildNanoBananaPrompt, CAMERA_MAP, LENS_MAP, FOCAL_PERSPECTIVE, APERTURE_EFFECT } from '../lib/promptUtils.js';
import { resolveMediaSrc } from '../lib/e2eMedia.js';
import { t } from '../lib/i18n.js';

import { useMediaSrc } from '../hooks/hooks.js';
import { registerPromptInserter } from '../app/promptTarget.js';
import { Icon } from '../ui/icons.jsx';
import {
  Button, Card, EmptyState, Pill, ProgressBar, SectionLabel, Segmented, Spinner, StudioLayout, cx,
} from '../ui/kit.jsx';
import { Modal } from '../ui/Modal.jsx';

import { CameraControls } from './CameraControls.jsx';
import { AuthModal } from '../dialogs/AuthModal.jsx';

const CINEMA_PREFERENCES_KEY = 'cinema_generation_preferences';
const CINEMA_HISTORY_KEY = 'cinema_history';
const CINEMA_ASPECT_RATIOS = ['16:9', '21:9', '9:16', '1:1', '4:5'];
const CINEMA_RESOLUTIONS = ['1K', '2K', '4K'];

// Behaviorally identical to normalizeCinemaPreferences in components/CinemaStudio.js
// (the old file is untouched; the persistence test imports the normalizer from there).
function normalizeCinemaPreferences(value) {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return null;
  const camera = Object.keys(CAMERA_MAP).includes(value.camera) ? value.camera : Object.keys(CAMERA_MAP)[0];
  const lens = Object.keys(LENS_MAP).includes(value.lens) ? value.lens : Object.keys(LENS_MAP)[0];
  const focalOptions = Object.keys(FOCAL_PERSPECTIVE).map(Number);
  const focal = focalOptions.includes(Number(value.focal)) ? Number(value.focal) : 35;
  const aperture = Object.keys(APERTURE_EFFECT).includes(value.aperture) ? value.aperture : 'f/1.4';
  return {
    aspect_ratio: CINEMA_ASPECT_RATIOS.includes(value.aspect_ratio) ? value.aspect_ratio : '16:9',
    resolution: CINEMA_RESOLUTIONS.includes(value.resolution) ? value.resolution : '2K',
    camera,
    lens,
    focal,
    aperture,
  };
}

function createEngine() {
  let persisted = null;
  try {
    persisted = normalizeCinemaPreferences(JSON.parse(localStorage.getItem(CINEMA_PREFERENCES_KEY) || 'null'));
  } catch { /* corrupted prefs — boot with defaults */ }
  const settings = persisted || {
    aspect_ratio: '16:9',
    resolution: '2K',
    camera: Object.keys(CAMERA_MAP)[0],
    lens: Object.keys(LENS_MAP)[0],
    focal: 35,
    aperture: 'f/1.4',
  };
  let history = [];
  try {
    const saved = JSON.parse(localStorage.getItem(CINEMA_HISTORY_KEY) || '[]');
    if (Array.isArray(saved)) history = saved;
  } catch { /* ignore */ }
  return { settings, history, prompt: '', generating: false, viewerUrl: null, authOpen: false };
}

function MetaRow({ label, value }) {
  if (value == null || value === '') return null;
  return (
    <div className="flex items-baseline gap-3">
      <span className="w-20 shrink-0 text-[11px] font-medium uppercase tracking-[0.06em] text-ink3">{label}</span>
      <span className="min-w-0 break-words font-mono text-xs leading-relaxed text-ink1">{String(value)}</span>
    </div>
  );
}

function CinemaGalleryCard({ entry, active, onOpen, onDownload }) {
  const src = useMediaSrc(entry.url);
  const setup = entry.settings || {};
  return (
    <div
      className={cx(
        'group relative cursor-pointer overflow-hidden rounded-lg border bg-bg2 transition-colors duration-150',
        active ? 'border-honey' : 'border-line1 hover:border-line2',
      )}
      onClick={onOpen}
      role="button"
      tabIndex={0}
      onKeyDown={(e) => { if (e.key === 'Enter') onOpen(); }}
    >
      {/* Not lazy — see GalleryAndViewer: a lazy image in a strip that never
          scrolls stays deferred forever. */}
      <img
        src={src}
        alt={setup.prompt?.substring(0, 30) || 'Cinema shot'}
        className="aspect-square w-full object-cover"
      />
      <div className="pointer-events-none absolute inset-x-0 bottom-0 bg-gradient-to-t from-bg0/90 to-transparent p-2 pt-6 opacity-0 transition-opacity duration-150 group-hover:opacity-100">
        <div className="truncate text-[11px] text-ink1">{setup.prompt || '—'}</div>
        <div className="truncate font-mono text-[10px] text-ink3">{setup.camera || ''}</div>
      </div>
      <div className="absolute right-1.5 top-1.5 flex gap-1 opacity-0 transition-opacity duration-150 group-hover:opacity-100">
        <button
          type="button"
          title={t('cinema.download')}
          aria-label="Download shot"
          className="grid h-7 w-7 place-items-center rounded-md border border-line1 bg-bg0/80 text-ink1 transition-colors hover:border-line2 hover:bg-bg1"
          onClick={(e) => { e.stopPropagation(); onDownload(); }}
        >
          <Icon name="download" size={13} />
        </button>
      </div>
    </div>
  );
}

function CinemaViewer({ url, entry, generating, onClose, onLoadSetup, onRegenerate, onDownload, onNew }) {
  const src = useMediaSrc(url);
  const setup = entry?.settings || {};
  return (
    <Modal
      open
      onClose={onClose}
      title="Cinema shot"
      size="xl"
      footer={
        <>
          <Button variant="ghost" onClick={onNew}>{t('cinema.newShot')}</Button>
          <Button variant="neutral" onClick={onLoadSetup}>{t('cinema.load')}</Button>
          <Button variant="neutral" loading={generating} onClick={onRegenerate}>{t('cinema.regenerate')}</Button>
          <Button variant="primary" onClick={onDownload}>{t('cinema.download')}</Button>
        </>
      }
    >
      <div className="flex flex-col gap-4">
        <div className="grid place-items-center overflow-hidden rounded-lg border border-line1 bg-bg0">
          <img src={src} alt={setup.prompt || 'Cinema shot'} className="max-h-[52vh] w-auto max-w-full object-contain" />
        </div>
        <div className="flex flex-col gap-1.5">
          <MetaRow label="Prompt" value={setup.prompt} />
          <MetaRow label="Camera" value={setup.camera} />
          <MetaRow label="Lens" value={setup.lens} />
          <MetaRow label="Focal" value={setup.focal != null ? `${setup.focal}mm` : ''} />
          <MetaRow label="Aperture" value={setup.aperture} />
          <MetaRow label="Aspect" value={setup.aspect_ratio} />
          <MetaRow label="Resolution" value={setup.resolution} />
        </div>
      </div>
    </Modal>
  );
}

export function CinemaStudio({ active = true } = {}) {
  const engineRef = useRef(null);
  if (!engineRef.current) engineRef.current = createEngine();
  const s = engineRef.current;
  const [, setTick] = useState(0);
  const bump = () => setTick((n) => n + 1);

  const promptRef = useRef(null);
  const authRetryRef = useRef(null);

  const persist = () => {
    const prefs = normalizeCinemaPreferences(s.settings);
    if (!prefs) return;
    try { localStorage.setItem(CINEMA_PREFERENCES_KEY, JSON.stringify(prefs)); } catch { /* quota */ }
  };

  const setSetting = (patch) => {
    s.settings = { ...s.settings, ...patch };
    persist();
    bump();
  };

  const setPrompt = (value) => {
    s.prompt = value;
    bump();
  };

  const addToHistory = (entry) => {
    s.history.unshift(entry);
    try { localStorage.setItem(CINEMA_HISTORY_KEY, JSON.stringify(s.history.slice(0, 50))); } catch { /* quota */ }
    bump();
  };

  // Restore a past shot's rig + prompt into the composer (old loadHistoryItem).
  const loadSetup = (entry) => {
    if (entry?.settings) {
      s.settings = {
        aspect_ratio: entry.settings.aspect_ratio,
        resolution: entry.settings.resolution || '2K',
        camera: entry.settings.camera,
        lens: entry.settings.lens,
        focal: entry.settings.focal,
        aperture: entry.settings.aperture,
      };
      s.prompt = entry.settings.prompt || '';
      persist();
    }
    s.viewerUrl = null;
    bump();
    promptRef.current?.focus();
  };

  const downloadShot = async (url, filename) => {
    try {
      const response = await fetch(await resolveMediaSrc(url));
      const blob = await response.blob();
      const blobUrl = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = blobUrl;
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(blobUrl);
    } catch {
      window.open(url, '_blank');
    }
  };

  const generate = async () => {
    const basePrompt = s.prompt.trim();
    if (!basePrompt) return;

    const apiKey = localStorage.getItem('muapi_key');
    if (!apiKey) {
      authRetryRef.current = () => generate();
      s.authOpen = true;
      bump();
      return;
    }

    s.generating = true;
    bump();

    const finalPrompt = buildNanoBananaPrompt(
      basePrompt,
      s.settings.camera,
      s.settings.lens,
      s.settings.focal,
      s.settings.aperture,
    );

    try {
      const res = await muapi.generateImage({
        model: 'nano-banana-pro',
        prompt: finalPrompt,
        aspect_ratio: s.settings.aspect_ratio,
        resolution: (s.settings.resolution || '1k').toLowerCase(),
        negative_prompt: 'blurry, low quality, distortion, bad composition',
      });

      if (res && res.url) {
        addToHistory({
          url: res.url,
          timestamp: Date.now(),
          settings: {
            prompt: basePrompt,
            ...s.settings,
            resolution: s.settings.resolution,
          },
        });
        s.viewerUrl = res.url;
      } else {
        throw new Error('No Data');
      }
    } catch (e) {
      console.error(e);
      toast.error(t('cinema.generationFailed') + e.message);
    } finally {
      s.generating = false;
      bump();
    }
  };

  // Fix for the old broken Regenerate: restore the shot's setup, then generate.
  const regenerateFrom = (entry) => {
    if (entry?.settings) {
      s.settings = {
        aspect_ratio: entry.settings.aspect_ratio,
        resolution: entry.settings.resolution || '2K',
        camera: entry.settings.camera,
        lens: entry.settings.lens,
        focal: entry.settings.focal,
        aperture: entry.settings.aperture,
      };
      s.prompt = entry.settings.prompt || '';
      persist();
    }
    s.viewerUrl = null;
    bump();
    void generate();
  };

  const newShot = () => {
    s.viewerUrl = null;
    s.prompt = '';
    bump();
    promptRef.current?.focus();
  };

  // Explore dock / hub bridges insert into this studio's prompt — only while it is
  // the visible studio (studios stay mounted-hidden after first visit).
  useEffect(() => {
    if (!active) return undefined;
    return registerPromptInserter((text) => {
      const current = s.prompt;
      const needsNewline = current && !current.endsWith('\n');
      s.prompt = `${current}${needsNewline ? '\n' : ''}${text}`;
      bump();
      promptRef.current?.focus();
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [active]);

  // Prompt textarea auto-grow (same 150/250px caps as the old oninput).
  useEffect(() => {
    const el = promptRef.current;
    if (!el) return;
    el.style.height = 'auto';
    const maxHeight = window.innerWidth < 768 ? 150 : 250;
    el.style.height = `${Math.min(el.scrollHeight, maxHeight)}px`;
  });

  const recipePreview = buildNanoBananaPrompt('', s.settings.camera, s.settings.lens, s.settings.focal, s.settings.aperture);
  const viewerEntry = s.viewerUrl ? s.history.find((e) => e.url === s.viewerUrl) : null;

  const panel = (
    <>
      <div className="flex flex-col gap-3">
        <SectionLabel>{t('cinema.cameraBuilder')}</SectionLabel>
        <CameraControls value={s.settings} onChange={(next) => setSetting(next)} />
      </div>

      <div className="flex flex-col gap-1.5">
        <SectionLabel>{t('cinema.preview')}</SectionLabel>
        <div className="rounded-md border border-line1 bg-bg2 px-3 py-2 text-[11px] leading-relaxed text-ink2">
          {recipePreview || t('cinema.selectSettings')}
        </div>
      </div>

      <div className="flex flex-col gap-3">
        <SectionLabel>Format</SectionLabel>
        <div className="flex flex-col gap-1.5">
          <span className="text-xs font-medium text-ink2">Aspect ratio</span>
          <Segmented size="sm" value={s.settings.aspect_ratio} onChange={(v) => setSetting({ aspect_ratio: v })} options={CINEMA_ASPECT_RATIOS} />
        </div>
        <div className="flex flex-col gap-1.5">
          <span className="text-xs font-medium text-ink2">Resolution</span>
          <Segmented size="sm" value={s.settings.resolution} onChange={(v) => setSetting({ resolution: v })} options={CINEMA_RESOLUTIONS} />
        </div>
      </div>

      <div className="flex flex-col gap-2">
        <SectionLabel>Engine</SectionLabel>
        <Pill tone="neutral" className="self-start font-mono">
          <Icon name="cloud" size={12} />
          nano-banana-pro
        </Pill>
      </div>
    </>
  );

  const composer = (
    <div className="mx-auto flex w-full max-w-4xl flex-col gap-2">
      <div className="flex flex-col gap-2 rounded-lg border border-line1 bg-bg1 p-2.5 transition-colors focus-within:border-honey/40">
        <textarea
          ref={promptRef}
          rows={1}
          placeholder={t('cinema.placeholder')}
          value={s.prompt}
          onChange={(e) => setPrompt(e.target.value)}
          className="max-h-[150px] min-h-[40px] w-full resize-none overflow-y-auto border-none bg-transparent px-1 pt-1 text-[15px] leading-relaxed text-ink1 outline-none placeholder:text-ink3 md:max-h-[250px]"
        />
        <div className="flex flex-wrap items-center gap-1.5">
          <Pill tone="neutral" className="hidden font-mono sm:inline-flex" title={t('cinema.cameraSettings')}>
            <Icon name="camera" size={12} />
            {`${s.settings.camera} · ${s.settings.focal}mm · ${s.settings.aperture}`}
          </Pill>
          <div className="min-w-2 flex-1" />
          <Button
            variant="primary"
            size="lg"
            loading={s.generating}
            onClick={generate}
            title={t('cinema.generateBtn')}
            className="min-w-[130px]"
          >
            {s.generating ? t('cinema.shooting') : t('cinema.generateBtn')}
          </Button>
        </div>
      </div>
    </div>
  );

  return (
    <div className="flex min-h-0 flex-1 flex-col">
      <StudioLayout panel={panel} panelTitle={t('cinema.cameraBuilder')} composer={composer}>
        <div className="flex flex-col gap-4 p-4 md:p-5">
          {s.generating ? (
            <Card className="flex items-center gap-3 p-4">
              <Spinner size={16} className="text-honey" />
              <span className="text-[13px] text-ink2">{t('cinema.shooting')}</span>
              <div className="flex-1"><ProgressBar value={null} /></div>
            </Card>
          ) : null}

          {s.history.length === 0 && !s.generating ? (
            <EmptyState
              icon="camera"
              title="Shoot your first frame"
              hint="Set the camera rig on the left, describe your scene below, and press Generate."
              className="flex-1"
            />
          ) : (
            <>
              <div className="flex items-center justify-between gap-2">
                <SectionLabel>{t('cinema.history')}</SectionLabel>
                <span className="font-mono text-[11px] text-ink3">{s.history.length}</span>
              </div>
              <div className="grid gap-3 [grid-template-columns:repeat(auto-fill,minmax(200px,1fr))]">
                {s.history.map((entry, idx) => (
                  <CinemaGalleryCard
                    key={`${entry.url}-${entry.timestamp || idx}`}
                    entry={entry}
                    active={s.viewerUrl ? s.viewerUrl === entry.url : idx === 0}
                    onOpen={() => { s.viewerUrl = entry.url; bump(); }}
                    onDownload={() => downloadShot(entry.url, `cinema-shot-${Date.now()}.jpg`)}
                  />
                ))}
              </div>
            </>
          )}
        </div>
      </StudioLayout>

      {s.viewerUrl ? (
        <CinemaViewer
          url={s.viewerUrl}
          entry={viewerEntry}
          generating={s.generating}
          onClose={() => { s.viewerUrl = null; bump(); promptRef.current?.focus(); }}
          onLoadSetup={() => loadSetup(viewerEntry)}
          onRegenerate={() => regenerateFrom(viewerEntry)}
          onDownload={() => downloadShot(s.viewerUrl, `cinema-shot-${Date.now()}.jpg`)}
          onNew={newShot}
        />
      ) : null}

      {s.authOpen ? (
        <AuthModal
          onClose={() => { s.authOpen = false; authRetryRef.current = null; bump(); }}
          onSaved={() => {
            s.authOpen = false;
            bump();
            const retry = authRetryRef.current;
            authRetryRef.current = null;
            if (retry) retry();
          }}
        />
      ) : null}
    </div>
  );
}
