// Cinema Studio — React redesign of the retired vanilla studio.
// Camera-simulated image generation: a camera rig (body / lens / focal / aperture)
// compiles a cinematic prompt via buildNanoBananaPrompt, generated by nano-banana-pro.
//
// Port rules honored here:
// - src/lib/** consumed unchanged; buildNanoBananaPrompt assembles the final prompt
//   with identical ordering; the generateImage call shape is byte-preserved.
// - Preferences persist to localStorage 'cinema_generation_preferences' via the
//   shared normalizer in lib/studioPreferences.js — one definition, which the
//   generationSettingsPersistence test exercises directly.
// - History ('cinema_history', slice 0..50, same entry shape) goes through the
//   studio history helpers in lib/hivemindStudio.js: in studio mode they are
//   no-ops, so a prompt never lands on disk in the clear — the same rule the
//   Image and Video studios follow. Standalone keeps plain localStorage.
// - Every media src goes through useMediaSrc (E2E decrypt, fail-open); downloads
//   go through the one shared downloader (lib/downloadMedia.js).
// - alert() → toast.error(); the two competing camera UIs (full-screen wheel overlay
//   + collapsible builder) collapse to ONE controlled rig in the left panel, which
//   fixes the old overlay/builder desync and body-mounted overlay leak for free.
// - The old "Regenerate clears the prompt then re-clicks Generate (no-ops)" bug is
//   fixed: Regenerate restores that shot's setup and generates. (Documented deviation.)
import { useEffect, useRef, useState } from 'react';
import { toast } from 'react-hot-toast';

import { muapiRow, needsBrowserKey, runImage } from '../lib/modelRunner.js';
import { buildNanoBananaPrompt, CAMERA_MAP, LENS_MAP } from '../lib/promptUtils.js';
import { downloadMedia } from '../lib/downloadMedia.js';
import { imageDownloadName } from '../lib/downloadNames.js';
import { formatElapsed } from '../lib/genProgress.js';
import { loadStudioGenerationHistory, saveStudioGenerationHistory } from '../lib/hivemindStudio.js';
import { toastMuapiError } from './lipsync/muapiErrorToast.jsx';
import {
  CINEMA_ASPECT_RATIOS,
  CINEMA_PREFERENCES_KEY,
  CINEMA_RESOLUTIONS,
  normalizeCinemaPreferences,
} from '../lib/studioPreferences.js';
import { t, zh } from '../lib/i18n.js';

import { useMediaSrc } from '../hooks/hooks.js';
import { registerPromptInserter } from '../app/promptTarget.js';
import { Icon } from '../ui/icons.jsx';
import {
  AspectRatioPicker, Button, Card, EmptyState, IconButton, Pill, ProgressBar, SectionLabel, Segmented, Spinner, StudioLayout, cx,
} from '../ui/kit.jsx';
import { ConfirmModal, Modal } from '../ui/Modal.jsx';

import { CameraControls } from './CameraControls.jsx';
import { MetaRow } from './lipsync/MetaRow.jsx';
import { AuthModal } from '../dialogs/AuthModal.jsx';

const CINEMA_HISTORY_KEY = 'cinema_history';
const CINEMA_HISTORY_LIMIT = 50;
const CINEMA_MODEL = 'nano-banana-pro';

function createEngine() {
  let persisted = null;
  try {
    persisted = normalizeCinemaPreferences(JSON.parse(localStorage.getItem(CINEMA_PREFERENCES_KEY) || 'null'));
  } catch { /* corrupted prefs — boot with defaults */ }
  const settings = persisted || {
    aspect_ratio: '16:9',
    resolution: '2K',
    camera: Object.keys(CAMERA_MAP)[0],
    lens: Object.keys(LENS_MAP)[0],
    focal: 35,
    aperture: 'f/1.4',
  };
  return {
    settings,
    history: loadStudioGenerationHistory(CINEMA_HISTORY_KEY),
    prompt: '',
    generating: false,
    startedAt: 0,
    viewerUrl: null,
    authOpen: false,
    confirmDelete: null,
  };
}

function CinemaGalleryCard({ entry, active, onOpen, onDownload, onDelete }) {
  const src = useMediaSrc(entry.url);
  const setup = entry.settings || {};
  return (
    <div
      className={cx(
        'group relative cursor-pointer overflow-hidden rounded-lg border bg-bg2 transition-colors duration-150',
        active ? 'border-honey' : 'border-line1 hover:border-line2',
      )}
      onClick={onOpen}
      role="button"
      tabIndex={0}
      onKeyDown={(e) => { if (e.key === 'Enter') onOpen(); }}
    >
      {/* Not lazy — see GalleryAndViewer: a lazy image in a strip that never
          scrolls stays deferred forever. */}
      <img
        src={src}
        alt={setup.prompt?.substring(0, 30) || (zh() ? '电影镜头' : 'Cinema shot')}
        className="aspect-square w-full object-cover"
      />
      <div className="pointer-events-none absolute inset-x-0 bottom-0 bg-gradient-to-t from-bg0/90 to-transparent p-2 pt-6 opacity-0 transition-opacity duration-150 group-hover:opacity-100">
        <div className="truncate text-[11px] text-ink1">{setup.prompt || '—'}</div>
        <div className="truncate font-mono text-[10px] text-ink3">{setup.camera || ''}</div>
      </div>
      <div className="absolute right-1.5 top-1.5 flex gap-1 opacity-0 transition-opacity duration-150 group-hover:opacity-100 focus-within:opacity-100">
        <IconButton
          icon="download"
          size="sm"
          label={t('cinema.download')}
          className="border border-line1 bg-bg0/80 text-ink1 hover:border-line2 hover:bg-bg1"
          onClick={(e) => { e.stopPropagation(); onDownload(); }}
        />
        <IconButton
          icon="trash"
          size="sm"
          label={zh() ? '从历史记录中移除' : 'Remove from history'}
          className="border border-line1 bg-bg0/80 text-ink1 hover:border-danger hover:bg-danger-tint hover:text-danger"
          onClick={(e) => { e.stopPropagation(); onDelete(); }}
        />
      </div>
    </div>
  );
}

function CinemaViewer({ url, entry, generating, onClose, onLoadSetup, onRegenerate, onDownload, onNew }) {
  const src = useMediaSrc(url);
  const setup = entry?.settings || {};
  return (
    <Modal
      open
      onClose={onClose}
      title={zh() ? '电影镜头' : 'Cinema shot'}
      size="xl"
      footer={
        <>
          <Button variant="ghost" onClick={onNew}>{t('cinema.newShot')}</Button>
          <Button variant="neutral" onClick={onLoadSetup} title={zh() ? '把这张镜头的机位与提示词载入编辑器' : 'Put this shot’s rig and prompt back in the composer'}>
            {t('cinema.load')}
          </Button>
          <Button
            variant="neutral"
            icon="refresh"
            loading={generating}
            onClick={onRegenerate}
            title={zh() ? '用这张镜头的设置再生成一次' : 'Runs again with this shot’s rig and prompt'}
          >
            {t('cinema.regenerate')}
          </Button>
          <Button variant="primary" icon="download" onClick={onDownload}>{t('cinema.download')}</Button>
        </>
      }
    >
      <div className="flex flex-col gap-4">
        <div className="grid place-items-center overflow-hidden rounded-lg border border-line1 bg-bg0">
          <img src={src} alt={setup.prompt || 'Cinema shot'} className="max-h-[52vh] w-auto max-w-full object-contain" />
        </div>
        <div className="flex flex-col gap-1.5">
          <MetaRow label={zh() ? '提示词' : 'Prompt'} value={setup.prompt} mono={false} />
          <MetaRow label={t('cinema.camera')} value={setup.camera} />
          <MetaRow label={t('cinema.lens')} value={setup.lens} />
          <MetaRow label={t('cinema.focal')} value={setup.focal != null ? `${setup.focal}mm` : ''} />
          <MetaRow label={t('cinema.aperture')} value={setup.aperture} />
          <MetaRow label={zh() ? '比例' : 'Aspect'} value={setup.aspect_ratio} />
          <MetaRow label={zh() ? '分辨率' : 'Resolution'} value={setup.resolution} />
          <MetaRow label={zh() ? '生成时间' : 'Created'} value={entry?.timestamp ? new Date(entry.timestamp).toLocaleString() : ''} mono={false} />
        </div>
      </div>
    </Modal>
  );
}

export function CinemaStudio({ active = true } = {}) {
  const engineRef = useRef(null);
  if (!engineRef.current) engineRef.current = createEngine();
  const s = engineRef.current;
  const [, setTick] = useState(0);
  const bump = () => setTick((n) => n + 1);

  const promptRef = useRef(null);
  const authRetryRef = useRef(null);

  const persist = () => {
    const prefs = normalizeCinemaPreferences(s.settings);
    if (!prefs) return;
    try { localStorage.setItem(CINEMA_PREFERENCES_KEY, JSON.stringify(prefs)); } catch { /* quota */ }
  };

  const setSetting = (patch) => {
    s.settings = { ...s.settings, ...patch };
    persist();
    bump();
  };

  const setPrompt = (value) => {
    s.prompt = value;
    bump();
  };

  const saveHistory = () => saveStudioGenerationHistory(CINEMA_HISTORY_KEY, s.history, CINEMA_HISTORY_LIMIT);

  const addToHistory = (entry) => {
    s.history.unshift(entry);
    s.history = s.history.slice(0, CINEMA_HISTORY_LIMIT);
    saveHistory();
    bump();
  };

  const removeFromHistory = (entry) => {
    s.history = s.history.filter((item) => item !== entry);
    if (s.viewerUrl === entry.url) s.viewerUrl = null;
    saveHistory();
    bump();
  };

  // Restore a past shot's rig + prompt into the composer (old loadHistoryItem).
  const loadSetup = (entry) => {
    if (entry?.settings) {
      s.settings = {
        aspect_ratio: entry.settings.aspect_ratio,
        resolution: entry.settings.resolution || '2K',
        camera: entry.settings.camera,
        lens: entry.settings.lens,
        focal: entry.settings.focal,
        aperture: entry.settings.aperture,
      };
      s.prompt = entry.settings.prompt || '';
      persist();
    }
    s.viewerUrl = null;
    bump();
    promptRef.current?.focus();
  };

  const downloadShot = (entry) => downloadMedia(entry.url, imageDownloadName(CINEMA_MODEL, entry.timestamp));

  const generate = async () => {
    const basePrompt = s.prompt.trim();
    if (!basePrompt) {
      toast.error(zh() ? '请先描述场景。' : 'Describe the scene first — the prompt is empty.');
      promptRef.current?.focus();
      return;
    }
    if (s.generating) return;

    // Only when NEITHER this machine's shared store nor this browser has the
    // key. A machine that already holds MUAPI_API_KEY runs straight through.
    if (needsBrowserKey(muapiRow(CINEMA_MODEL))) {
      authRetryRef.current = () => generate();
      s.authOpen = true;
      bump();
      return;
    }

    s.generating = true;
    s.startedAt = Date.now();
    bump();

    const finalPrompt = buildNanoBananaPrompt(
      basePrompt,
      s.settings.camera,
      s.settings.lens,
      s.settings.focal,
      s.settings.aperture,
    );

    try {
      // Through the one dispatcher, like every other studio: the PROVIDER
      // decides the transport, never the call site. `extra.muapi` is also this
      // call's declaration that a MUAPI payload is what it built — a row that
      // resolved anywhere else is refused rather than sent this shape.
      const res = await runImage({
        row: muapiRow(CINEMA_MODEL),
        shared: { prompt: finalPrompt, aspect_ratio: s.settings.aspect_ratio },
        extra: {
          muapi: {
            resolution: (s.settings.resolution || '2K').toLowerCase(),
            negative_prompt: 'blurry, low quality, distortion, bad composition',
          },
        },
      });

      if (res && res.url) {
        addToHistory({
          url: res.url,
          timestamp: Date.now(),
          settings: {
            prompt: basePrompt,
            ...s.settings,
            resolution: s.settings.resolution,
          },
        });
        s.viewerUrl = res.url;
      } else {
        throw new Error('No Data');
      }
    } catch (e) {
      console.error(e);
      toastMuapiError(e, { prefix: t('cinema.generationFailed').replace(/:\s*$/, '') });
    } finally {
      s.generating = false;
      s.startedAt = 0;
      bump();
    }
  };

  // Fix for the old broken Regenerate: restore the shot's setup, then generate.
  const regenerateFrom = (entry) => {
    if (entry?.settings) {
      s.settings = {
        aspect_ratio: entry.settings.aspect_ratio,
        resolution: entry.settings.resolution || '2K',
        camera: entry.settings.camera,
        lens: entry.settings.lens,
        focal: entry.settings.focal,
        aperture: entry.settings.aperture,
      };
      s.prompt = entry.settings.prompt || '';
      persist();
    }
    s.viewerUrl = null;
    bump();
    void generate();
  };

  const newShot = () => {
    s.viewerUrl = null;
    s.prompt = '';
    bump();
    promptRef.current?.focus();
  };

  // Explore dock / hub bridges insert into this studio's prompt — only while it is
  // the visible studio (studios stay mounted-hidden after first visit).
  useEffect(() => {
    if (!active) return undefined;
    return registerPromptInserter((text) => {
      const current = s.prompt;
      const needsNewline = current && !current.endsWith('\n');
      s.prompt = `${current}${needsNewline ? '\n' : ''}${text}`;
      bump();
      promptRef.current?.focus();
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [active]);

  // Prompt textarea auto-grow (same 150/250px caps as the old oninput).
  useEffect(() => {
    const el = promptRef.current;
    if (!el) return;
    el.style.height = 'auto';
    const maxHeight = window.innerWidth < 768 ? 150 : 250;
    el.style.height = `${Math.min(el.scrollHeight, maxHeight)}px`;
  });

  // Elapsed readout on the progress card: MUAPI gives no progress, so time is
  // the only honest thing to show while a shot is out.
  useEffect(() => {
    if (!s.generating) return undefined;
    const id = window.setInterval(bump, 1000);
    return () => window.clearInterval(id);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [s.generating]);

  const recipePreview = buildNanoBananaPrompt('', s.settings.camera, s.settings.lens, s.settings.focal, s.settings.aperture);
  const viewerEntry = s.viewerUrl ? s.history.find((e) => e.url === s.viewerUrl) : null;
  const hasPrompt = Boolean(s.prompt.trim());

  const panel = (
    <>
      <div className="flex flex-col gap-3">
        <SectionLabel>{t('cinema.cameraBuilder')}</SectionLabel>
        <CameraControls value={s.settings} onChange={(next) => setSetting(next)} />
      </div>

      <div className="flex flex-col gap-1.5">
        <SectionLabel>{t('cinema.preview')}</SectionLabel>
        <div className="rounded-md border border-line1 bg-bg2 px-3 py-2 text-[11px] leading-relaxed text-ink2">
          {recipePreview || t('cinema.selectSettings')}
        </div>
      </div>

      <div className="flex flex-col gap-3">
        <SectionLabel>{zh() ? '画幅' : 'Format'}</SectionLabel>
        <div className="flex flex-col gap-1.5">
          <span className="text-xs font-medium text-ink2">{zh() ? '宽高比' : 'Aspect ratio'}</span>
          <AspectRatioPicker
            options={CINEMA_ASPECT_RATIOS}
            value={s.settings.aspect_ratio}
            onChange={(v) => setSetting({ aspect_ratio: v })}
          />
        </div>
        <div className="flex flex-col gap-1.5">
          <span className="text-xs font-medium text-ink2">{zh() ? '分辨率' : 'Resolution'}</span>
          <Segmented size="sm" value={s.settings.resolution} onChange={(v) => setSetting({ resolution: v })} options={CINEMA_RESOLUTIONS} />
        </div>
      </div>

      <div className="flex flex-col gap-2">
        <SectionLabel>{zh() ? '引擎' : 'Engine'}</SectionLabel>
        <Pill tone="neutral" className="self-start font-mono">
          <Icon name="cloud" size={12} />
          {CINEMA_MODEL}
        </Pill>
        <p className="text-[11px] leading-relaxed text-ink3">
          {zh() ? '在 MUAPI（云端）运行 — 提示词会发送到那里。' : 'Runs on MUAPI (cloud) — prompts are sent there.'}
        </p>
      </div>
    </>
  );

  const composer = (
    <div className="mx-auto flex w-full max-w-4xl flex-col gap-2">
      <div className="flex flex-col gap-2 rounded-lg border border-line1 bg-bg1 p-2.5 transition-colors focus-within:border-honey/40">
        <textarea
          ref={promptRef}
          rows={1}
          placeholder={t('cinema.placeholder')}
          value={s.prompt}
          onChange={(e) => setPrompt(e.target.value)}
          onKeyDown={(e) => {
            if (e.key === 'Enter' && (e.metaKey || e.ctrlKey)) { e.preventDefault(); void generate(); }
          }}
          className="max-h-[150px] min-h-[40px] w-full resize-none overflow-y-auto border-none bg-transparent px-1 pt-1 text-[15px] leading-relaxed text-ink1 outline-none placeholder:text-ink3 md:max-h-[250px]"
        />
        <div className="flex flex-wrap items-center gap-1.5">
          <Pill tone="neutral" className="hidden font-mono sm:inline-flex" title={t('cinema.cameraSettings')}>
            <Icon name="camera" size={12} />
            {`${s.settings.camera} · ${s.settings.focal}mm · ${s.settings.aperture}`}
          </Pill>
          <div className="min-w-2 flex-1" />
          <Button
            variant="primary"
            size="lg"
            loading={s.generating}
            disabled={!hasPrompt}
            onClick={generate}
            title={hasPrompt
              ? (zh() ? '生成（⌘/Ctrl+Enter）' : 'Generate (⌘/Ctrl+Enter)')
              : (zh() ? '请先描述场景' : 'Describe the scene first')}
            className="min-w-[130px]"
          >
            {s.generating ? t('cinema.shooting') : t('cinema.generateBtn')}
          </Button>
        </div>
      </div>
    </div>
  );

  return (
    <div className="flex min-h-0 flex-1 flex-col">
      <StudioLayout panel={panel} panelTitle={t('cinema.cameraBuilder')} composer={composer}>
        <div className="flex flex-col gap-4 p-4 md:p-5">
          {s.generating ? (
            <Card className="flex items-center gap-3 p-4">
              <Spinner size={16} className="text-honey" />
              <span className="text-[13px] text-ink2">{t('cinema.shooting')}</span>
              <div className="flex-1"><ProgressBar value={null} label={t('cinema.shooting')} /></div>
              <span className="shrink-0 font-mono text-[11px] text-ink3">{formatElapsed(Date.now() - s.startedAt)}</span>
            </Card>
          ) : null}

          {s.history.length === 0 && !s.generating ? (
            <EmptyState
              icon="camera"
              title={zh() ? '拍摄你的第一帧' : 'Shoot your first frame'}
              hint={zh() ? '在左侧设置机位，在下方描述场景，然后按生成。' : 'Set the camera rig on the left, describe your scene below, and press Generate.'}
              className="flex-1"
            />
          ) : (
            <>
              <div className="flex items-center justify-between gap-2">
                <SectionLabel>{t('cinema.history')}</SectionLabel>
                <span className="font-mono text-[11px] text-ink3">{s.history.length}</span>
              </div>
              <div className="grid gap-3 [grid-template-columns:repeat(auto-fill,minmax(200px,1fr))]">
                {s.history.map((entry, idx) => (
                  <CinemaGalleryCard
                    key={`${entry.url}-${entry.timestamp || idx}`}
                    entry={entry}
                    active={s.viewerUrl ? s.viewerUrl === entry.url : idx === 0}
                    onOpen={() => { s.viewerUrl = entry.url; bump(); }}
                    onDownload={() => downloadShot(entry)}
                    onDelete={() => { s.confirmDelete = entry; bump(); }}
                  />
                ))}
              </div>
            </>
          )}
        </div>
      </StudioLayout>

      {s.viewerUrl ? (
        <CinemaViewer
          url={s.viewerUrl}
          entry={viewerEntry}
          generating={s.generating}
          onClose={() => { s.viewerUrl = null; bump(); promptRef.current?.focus(); }}
          onLoadSetup={() => loadSetup(viewerEntry)}
          onRegenerate={() => regenerateFrom(viewerEntry)}
          onDownload={() => (viewerEntry ? downloadShot(viewerEntry) : downloadMedia(s.viewerUrl, imageDownloadName(CINEMA_MODEL, Date.now())))}
          onNew={newShot}
        />
      ) : null}

      <ConfirmModal
        open={Boolean(s.confirmDelete)}
        onClose={() => { s.confirmDelete = null; bump(); }}
        onConfirm={() => { const entry = s.confirmDelete; s.confirmDelete = null; if (entry) removeFromHistory(entry); }}
        title={zh() ? '从历史记录中移除这张镜头？' : 'Remove this shot from history?'}
        body={zh() ? '只会从此工作室的列表中移除，不会删除任何文件。' : 'It leaves this studio’s list only — no file is deleted.'}
        confirmLabel={zh() ? '移除' : 'Remove'}
        cancelLabel={zh() ? '取消' : 'Cancel'}
      />

      {s.authOpen ? (
        <AuthModal
          onClose={() => { s.authOpen = false; authRetryRef.current = null; bump(); }}
          onSaved={() => {
            s.authOpen = false;
            bump();
            const retry = authRetryRef.current;
            authRetryRef.current = null;
            if (retry) retry();
          }}
        />
      ) : null}
    </div>
  );
}
